-- Bronze → Silver: type casting, cleanup, Cortex sentiment enrichment

USE DATABASE ATTRITION_ML;

TRUNCATE TABLE IF EXISTS SILVER.EMPLOYEE_CLEANSED;

INSERT INTO SILVER.EMPLOYEE_CLEANSED (
    EMPLOYEE_ID, EMPLOYEE_NAME, ROLE, DEPARTMENT, REGION,
    TENURE_YEARS, SALARY, PERFORMANCE_SCORE, MANAGER_RATING,
    PROMOTIONS_LAST_3_YEARS, FLIGHT_HOURS_YTD, OVERTIME_HOURS_MONTHLY,
    DAYS_SINCE_LAST_RAISE, TEAM_SIZE, REMOTE_ELIGIBLE,
    HIRE_DATE, TERMINATION_DATE, CHURNED,
    EXIT_SURVEY_TEXT, EXIT_SURVEY_SENTIMENT, CHURN_RISK_SCORE, LOADED_AT
)
SELECT
    TRIM(EMPLOYEE_ID),
    TRIM(EMPLOYEE_NAME),
    UPPER(TRIM(ROLE)),
    UPPER(TRIM(DEPARTMENT)),
    UPPER(TRIM(REGION)),
    TRY_CAST(TENURE_YEARS AS FLOAT),
    TRY_CAST(SALARY AS NUMBER(10,0)),
    TRY_CAST(PERFORMANCE_SCORE AS NUMBER(1,0)),
    TRY_CAST(MANAGER_RATING AS NUMBER(1,0)),
    TRY_CAST(PROMOTIONS_LAST_3_YEARS AS NUMBER(1,0)),
    TRY_CAST(FLIGHT_HOURS_YTD AS NUMBER(6,0)),
    TRY_CAST(OVERTIME_HOURS_MONTHLY AS FLOAT),
    TRY_CAST(DAYS_SINCE_LAST_RAISE AS NUMBER(5,0)),
    TRY_CAST(TEAM_SIZE AS NUMBER(3,0)),
    UPPER(TRIM(REMOTE_ELIGIBLE)),
    TRY_CAST(HIRE_DATE AS DATE),
    TRY_CAST(TERMINATION_DATE AS DATE),
    UPPER(TRIM(CHURNED)),
    EXIT_SURVEY_TEXT,
    -- Cortex sentiment on exit surveys (null for active employees)
    CASE
        WHEN EXIT_SURVEY_TEXT IS NOT NULL AND TRIM(EXIT_SURVEY_TEXT) != ''
        THEN SNOWFLAKE.CORTEX.SENTIMENT(EXIT_SURVEY_TEXT)
        ELSE NULL
    END,
    NULL,  -- churn_risk_score populated after model training
    LOADED_AT
FROM BRONZE.EMPLOYEE_RAW
WHERE EMPLOYEE_ID IS NOT NULL;
