-- Silver → Gold: ML-ready feature set with train/test split

USE DATABASE ATTRITION_ML;

TRUNCATE TABLE IF EXISTS GOLD.EMPLOYEE_ML_READY;

INSERT INTO GOLD.EMPLOYEE_ML_READY (
    EMPLOYEE_ID, ROLE, REGION,
    TENURE_YEARS, SALARY, PERFORMANCE_SCORE, MANAGER_RATING,
    PROMOTIONS_LAST_3_YEARS, OVERTIME_HOURS_MONTHLY,
    DAYS_SINCE_LAST_RAISE, TEAM_SIZE, REMOTE_ELIGIBLE,
    EXIT_SURVEY_SENTIMENT, CHURNED, SPLIT
)
SELECT
    EMPLOYEE_ID,
    ROLE,
    REGION,
    TENURE_YEARS,
    SALARY,
    PERFORMANCE_SCORE::FLOAT,
    MANAGER_RATING::FLOAT,
    PROMOTIONS_LAST_3_YEARS,
    OVERTIME_HOURS_MONTHLY,
    DAYS_SINCE_LAST_RAISE,
    TEAM_SIZE,
    CASE WHEN REMOTE_ELIGIBLE = 'Y' THEN 1 ELSE 0 END,
    -- backfill sentiment as 0 for active employees (no survey)
    COALESCE(EXIT_SURVEY_SENTIMENT, 0),
    CASE WHEN CHURNED = 'Y' THEN 1 ELSE 0 END,
    -- 80/20 train/test split, deterministic by employee_id hash
    CASE
        WHEN ABS(HASH(EMPLOYEE_ID)) % 10 < 8 THEN 'TRAIN'
        ELSE 'TEST'
    END
FROM SILVER.EMPLOYEE_CLEANSED
WHERE TENURE_YEARS IS NOT NULL
  AND SALARY IS NOT NULL
  AND PERFORMANCE_SCORE IS NOT NULL
  AND MANAGER_RATING IS NOT NULL
  AND OVERTIME_HOURS_MONTHLY IS NOT NULL
  AND DAYS_SINCE_LAST_RAISE IS NOT NULL;
