-- HR annotation table for qualitative context on at-risk employees
CREATE TABLE IF NOT EXISTS ATTRITION_ML.SILVER.HR_ANNOTATIONS (
    EMPLOYEE_ID         VARCHAR,
    ANNOTATION_TYPE     VARCHAR,
    ANNOTATION_TEXT     VARCHAR,
    CREATED_BY          VARCHAR,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    ACTIVE              BOOLEAN DEFAULT TRUE
);

GRANT INSERT, SELECT ON TABLE ATTRITION_ML.SILVER.HR_ANNOTATIONS TO ROLE ATTRITION_ROLE;
